/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.formatting2;

import com.google.inject.Inject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.xbase.lib.Extension;
import org.xtext.example.mydsl.services.SchoolGrammarAccess;

@SuppressWarnings("all")
public class SchoolFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private SchoolGrammarAccess _schoolGrammarAccess;
}
