/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl.SchoolRuntimeModule;
import org.xtext.example.mydsl.SchoolStandaloneSetup;
import org.xtext.example.mydsl.ide.SchoolIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SchoolIdeSetup extends SchoolStandaloneSetup {
  @Override
  public Injector createInjector() {
    SchoolRuntimeModule _schoolRuntimeModule = new SchoolRuntimeModule();
    SchoolIdeModule _schoolIdeModule = new SchoolIdeModule();
    return Guice.createInjector(Modules2.mixin(_schoolRuntimeModule, _schoolIdeModule));
  }
}
