/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.school.ui.internal.SchoolActivator;

public class SchoolUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SchoolActivator.getInstance().getInjector("org.xtext.example.mydsl.School");
	}

}
