/**
 *
 * $Id$
 */
package noorApps.validation;

import noorApps.TipoDato;

/**
 * A sample validator interface for {@link noorApps.Atributo}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AtributoValidator {
	boolean validate();

	boolean validateNombre(String value);
	boolean validateTipo(TipoDato value);
	boolean validateEsVisible(boolean value);
	boolean validateEsEditable(boolean value);
	boolean validateEsRequerido(boolean value);
	boolean validateEsTitulo(boolean value);
}
