/**
 *
 * $Id$
 */
package noorApps.validation;

import noorApps.Entidad;


/**
 * A sample validator interface for {@link noorApps.Detalle}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DetalleValidator {
	boolean validate();

	boolean validateEsFuerte(boolean value);

	boolean validateEntidad(Entidad value);

	boolean validateName(String value);

	boolean validateTitulo(String value);
}
