/**
 *
 * $Id$
 */
package noorApps.validation;

import noorApps.Atributo;
import noorApps.Detalle;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link noorApps.Entidad}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EntidadValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateTitulo(String value);
	boolean validateAtributo(EList<Atributo> value);
	boolean validateDescripcion(String value);
	boolean validateDetalles(EList<Detalle> value);
}
