/**
 *
 * $Id$
 */
package noorApps.validation;

import noorApps.Detalle;
import noorApps.Entidad;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link noorApps.Root}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RootValidator {
	boolean validate();

	boolean validateEntidad(EList<Entidad> value);
	boolean validateNombre(String value);
	boolean validateNavBarColorHex(String value);
	boolean validateTextColor(String value);
	boolean validateFloatingButtonColor(String value);

	boolean validateDetalles(EList<Detalle> value);
}
