/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.SchoolStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SchoolStandaloneSetup extends SchoolStandaloneSetupGenerated {
  public static void doSetup() {
    new SchoolStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
