/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class SchoolGrammarAccess extends AbstractGrammarElementFinder {
	
	public class RootElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.School.Root");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRootAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cApplicationKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNombreAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNombreEStringParserRuleCall_2_0 = (RuleCall)cNombreAssignment_2.eContents().get(0);
		private final RuleCall cTOPENBRACETerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Keyword cNavBarColorHexKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final RuleCall cEQUALSTerminalRuleCall_5 = (RuleCall)cGroup.eContents().get(5);
		private final Assignment cNavBarColorHexAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cNavBarColorHexEStringParserRuleCall_6_0 = (RuleCall)cNavBarColorHexAssignment_6.eContents().get(0);
		private final RuleCall cTSEMICOLONTerminalRuleCall_7 = (RuleCall)cGroup.eContents().get(7);
		private final Keyword cTextColorKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final RuleCall cEQUALSTerminalRuleCall_9 = (RuleCall)cGroup.eContents().get(9);
		private final Assignment cTextColorAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cTextColorEStringParserRuleCall_10_0 = (RuleCall)cTextColorAssignment_10.eContents().get(0);
		private final RuleCall cTSEMICOLONTerminalRuleCall_11 = (RuleCall)cGroup.eContents().get(11);
		private final Keyword cFloatingButtonColorKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final RuleCall cEQUALSTerminalRuleCall_13 = (RuleCall)cGroup.eContents().get(13);
		private final Assignment cFloatingButtonColorAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cFloatingButtonColorEStringParserRuleCall_14_0 = (RuleCall)cFloatingButtonColorAssignment_14.eContents().get(0);
		private final RuleCall cTSEMICOLONTerminalRuleCall_15 = (RuleCall)cGroup.eContents().get(15);
		private final Assignment cEntidadAssignment_16 = (Assignment)cGroup.eContents().get(16);
		private final RuleCall cEntidadEntidadParserRuleCall_16_0 = (RuleCall)cEntidadAssignment_16.eContents().get(0);
		private final Assignment cDetallesAssignment_17 = (Assignment)cGroup.eContents().get(17);
		private final RuleCall cDetallesDetalleParserRuleCall_17_0 = (RuleCall)cDetallesAssignment_17.eContents().get(0);
		private final RuleCall cTCLOSINGBRACETerminalRuleCall_18 = (RuleCall)cGroup.eContents().get(18);
		
		//Root:
		//	{Root}
		//	'Application' nombre=EString TOPENBRACE
		//	'navBarColorHex' EQUALS navBarColorHex=EString TSEMICOLON
		//	'textColor' EQUALS textColor=EString TSEMICOLON
		//	'floatingButtonColor' EQUALS floatingButtonColor=EString TSEMICOLON
		//	entidad+=Entidad+
		//	detalles+=Detalle*
		//	TCLOSINGBRACE;
		@Override public ParserRule getRule() { return rule; }
		
		//{Root} 'Application' nombre=EString TOPENBRACE 'navBarColorHex' EQUALS navBarColorHex=EString TSEMICOLON 'textColor'
		//EQUALS textColor=EString TSEMICOLON 'floatingButtonColor' EQUALS floatingButtonColor=EString TSEMICOLON
		//entidad+=Entidad+ detalles+=Detalle* TCLOSINGBRACE
		public Group getGroup() { return cGroup; }
		
		//{Root}
		public Action getRootAction_0() { return cRootAction_0; }
		
		//'Application'
		public Keyword getApplicationKeyword_1() { return cApplicationKeyword_1; }
		
		//nombre=EString
		public Assignment getNombreAssignment_2() { return cNombreAssignment_2; }
		
		//EString
		public RuleCall getNombreEStringParserRuleCall_2_0() { return cNombreEStringParserRuleCall_2_0; }
		
		//TOPENBRACE
		public RuleCall getTOPENBRACETerminalRuleCall_3() { return cTOPENBRACETerminalRuleCall_3; }
		
		//'navBarColorHex'
		public Keyword getNavBarColorHexKeyword_4() { return cNavBarColorHexKeyword_4; }
		
		//EQUALS
		public RuleCall getEQUALSTerminalRuleCall_5() { return cEQUALSTerminalRuleCall_5; }
		
		//navBarColorHex=EString
		public Assignment getNavBarColorHexAssignment_6() { return cNavBarColorHexAssignment_6; }
		
		//EString
		public RuleCall getNavBarColorHexEStringParserRuleCall_6_0() { return cNavBarColorHexEStringParserRuleCall_6_0; }
		
		//TSEMICOLON
		public RuleCall getTSEMICOLONTerminalRuleCall_7() { return cTSEMICOLONTerminalRuleCall_7; }
		
		//'textColor'
		public Keyword getTextColorKeyword_8() { return cTextColorKeyword_8; }
		
		//EQUALS
		public RuleCall getEQUALSTerminalRuleCall_9() { return cEQUALSTerminalRuleCall_9; }
		
		//textColor=EString
		public Assignment getTextColorAssignment_10() { return cTextColorAssignment_10; }
		
		//EString
		public RuleCall getTextColorEStringParserRuleCall_10_0() { return cTextColorEStringParserRuleCall_10_0; }
		
		//TSEMICOLON
		public RuleCall getTSEMICOLONTerminalRuleCall_11() { return cTSEMICOLONTerminalRuleCall_11; }
		
		//'floatingButtonColor'
		public Keyword getFloatingButtonColorKeyword_12() { return cFloatingButtonColorKeyword_12; }
		
		//EQUALS
		public RuleCall getEQUALSTerminalRuleCall_13() { return cEQUALSTerminalRuleCall_13; }
		
		//floatingButtonColor=EString
		public Assignment getFloatingButtonColorAssignment_14() { return cFloatingButtonColorAssignment_14; }
		
		//EString
		public RuleCall getFloatingButtonColorEStringParserRuleCall_14_0() { return cFloatingButtonColorEStringParserRuleCall_14_0; }
		
		//TSEMICOLON
		public RuleCall getTSEMICOLONTerminalRuleCall_15() { return cTSEMICOLONTerminalRuleCall_15; }
		
		//entidad+=Entidad+
		public Assignment getEntidadAssignment_16() { return cEntidadAssignment_16; }
		
		//Entidad
		public RuleCall getEntidadEntidadParserRuleCall_16_0() { return cEntidadEntidadParserRuleCall_16_0; }
		
		//detalles+=Detalle*
		public Assignment getDetallesAssignment_17() { return cDetallesAssignment_17; }
		
		//Detalle
		public RuleCall getDetallesDetalleParserRuleCall_17_0() { return cDetallesDetalleParserRuleCall_17_0; }
		
		//TCLOSINGBRACE
		public RuleCall getTCLOSINGBRACETerminalRuleCall_18() { return cTCLOSINGBRACETerminalRuleCall_18; }
	}
	public class DetalleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.School.Detalle");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cDetalleAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cDetailKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final RuleCall cTOPENBRACETerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Keyword cIsStrongKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final RuleCall cEQUALSTerminalRuleCall_5 = (RuleCall)cGroup.eContents().get(5);
		private final Assignment cEsFuerteAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cEsFuerteEBooleanParserRuleCall_6_0 = (RuleCall)cEsFuerteAssignment_6.eContents().get(0);
		private final RuleCall cTSEMICOLONTerminalRuleCall_7 = (RuleCall)cGroup.eContents().get(7);
		private final Assignment cEntidadAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final CrossReference cEntidadEntidadCrossReference_8_0 = (CrossReference)cEntidadAssignment_8.eContents().get(0);
		private final RuleCall cEntidadEntidadIDTerminalRuleCall_8_0_1 = (RuleCall)cEntidadEntidadCrossReference_8_0.eContents().get(1);
		private final RuleCall cTCLOSINGBRACETerminalRuleCall_9 = (RuleCall)cGroup.eContents().get(9);
		
		//Detalle:
		//	{Detalle}
		//	'Detail' name=ID TOPENBRACE
		//	'isStrong' EQUALS esFuerte=EBoolean TSEMICOLON
		//	entidad=[Entidad] TCLOSINGBRACE;
		@Override public ParserRule getRule() { return rule; }
		
		//{Detalle} 'Detail' name=ID TOPENBRACE 'isStrong' EQUALS esFuerte=EBoolean TSEMICOLON entidad=[Entidad] TCLOSINGBRACE
		public Group getGroup() { return cGroup; }
		
		//{Detalle}
		public Action getDetalleAction_0() { return cDetalleAction_0; }
		
		//'Detail'
		public Keyword getDetailKeyword_1() { return cDetailKeyword_1; }
		
		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//TOPENBRACE
		public RuleCall getTOPENBRACETerminalRuleCall_3() { return cTOPENBRACETerminalRuleCall_3; }
		
		//'isStrong'
		public Keyword getIsStrongKeyword_4() { return cIsStrongKeyword_4; }
		
		//EQUALS
		public RuleCall getEQUALSTerminalRuleCall_5() { return cEQUALSTerminalRuleCall_5; }
		
		//esFuerte=EBoolean
		public Assignment getEsFuerteAssignment_6() { return cEsFuerteAssignment_6; }
		
		//EBoolean
		public RuleCall getEsFuerteEBooleanParserRuleCall_6_0() { return cEsFuerteEBooleanParserRuleCall_6_0; }
		
		//TSEMICOLON
		public RuleCall getTSEMICOLONTerminalRuleCall_7() { return cTSEMICOLONTerminalRuleCall_7; }
		
		//entidad=[Entidad]
		public Assignment getEntidadAssignment_8() { return cEntidadAssignment_8; }
		
		//[Entidad]
		public CrossReference getEntidadEntidadCrossReference_8_0() { return cEntidadEntidadCrossReference_8_0; }
		
		//ID
		public RuleCall getEntidadEntidadIDTerminalRuleCall_8_0_1() { return cEntidadEntidadIDTerminalRuleCall_8_0_1; }
		
		//TCLOSINGBRACE
		public RuleCall getTCLOSINGBRACETerminalRuleCall_9() { return cTCLOSINGBRACETerminalRuleCall_9; }
	}
	public class EntidadElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.School.Entidad");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEntidadAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cEntityKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final RuleCall cTOPENBRACETerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Keyword cDescriptionKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final RuleCall cEQUALSTerminalRuleCall_5 = (RuleCall)cGroup.eContents().get(5);
		private final Assignment cDescripcionAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cDescripcionEStringParserRuleCall_6_0 = (RuleCall)cDescripcionAssignment_6.eContents().get(0);
		private final RuleCall cTSEMICOLONTerminalRuleCall_7 = (RuleCall)cGroup.eContents().get(7);
		private final Assignment cAtributoAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cAtributoAtributoParserRuleCall_8_0 = (RuleCall)cAtributoAssignment_8.eContents().get(0);
		private final Assignment cDetallesAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final CrossReference cDetallesDetalleCrossReference_9_0 = (CrossReference)cDetallesAssignment_9.eContents().get(0);
		private final RuleCall cDetallesDetalleIDTerminalRuleCall_9_0_1 = (RuleCall)cDetallesDetalleCrossReference_9_0.eContents().get(1);
		private final RuleCall cTCLOSINGBRACETerminalRuleCall_10 = (RuleCall)cGroup.eContents().get(10);
		
		//Entidad:
		//	{Entidad}
		//	'Entity' name=ID TOPENBRACE
		//	'description' EQUALS descripcion=EString TSEMICOLON
		//	atributo+=Atributo+
		//	detalles+=[Detalle]*
		//	TCLOSINGBRACE;
		@Override public ParserRule getRule() { return rule; }
		
		//{Entidad} 'Entity' name=ID TOPENBRACE 'description' EQUALS descripcion=EString TSEMICOLON atributo+=Atributo+
		//detalles+=[Detalle]* TCLOSINGBRACE
		public Group getGroup() { return cGroup; }
		
		//{Entidad}
		public Action getEntidadAction_0() { return cEntidadAction_0; }
		
		//'Entity'
		public Keyword getEntityKeyword_1() { return cEntityKeyword_1; }
		
		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//TOPENBRACE
		public RuleCall getTOPENBRACETerminalRuleCall_3() { return cTOPENBRACETerminalRuleCall_3; }
		
		//'description'
		public Keyword getDescriptionKeyword_4() { return cDescriptionKeyword_4; }
		
		//EQUALS
		public RuleCall getEQUALSTerminalRuleCall_5() { return cEQUALSTerminalRuleCall_5; }
		
		//descripcion=EString
		public Assignment getDescripcionAssignment_6() { return cDescripcionAssignment_6; }
		
		//EString
		public RuleCall getDescripcionEStringParserRuleCall_6_0() { return cDescripcionEStringParserRuleCall_6_0; }
		
		//TSEMICOLON
		public RuleCall getTSEMICOLONTerminalRuleCall_7() { return cTSEMICOLONTerminalRuleCall_7; }
		
		//atributo+=Atributo+
		public Assignment getAtributoAssignment_8() { return cAtributoAssignment_8; }
		
		//Atributo
		public RuleCall getAtributoAtributoParserRuleCall_8_0() { return cAtributoAtributoParserRuleCall_8_0; }
		
		//detalles+=[Detalle]*
		public Assignment getDetallesAssignment_9() { return cDetallesAssignment_9; }
		
		//[Detalle]
		public CrossReference getDetallesDetalleCrossReference_9_0() { return cDetallesDetalleCrossReference_9_0; }
		
		//ID
		public RuleCall getDetallesDetalleIDTerminalRuleCall_9_0_1() { return cDetallesDetalleIDTerminalRuleCall_9_0_1; }
		
		//TCLOSINGBRACE
		public RuleCall getTCLOSINGBRACETerminalRuleCall_10() { return cTCLOSINGBRACETerminalRuleCall_10; }
	}
	public class AtributoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.School.Atributo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAtributoAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cAttributeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNombreAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNombreEStringParserRuleCall_2_0 = (RuleCall)cNombreAssignment_2.eContents().get(0);
		private final RuleCall cTOPENBRACETerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Keyword cIsEditableKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final RuleCall cEQUALSTerminalRuleCall_5 = (RuleCall)cGroup.eContents().get(5);
		private final Assignment cEsEditableAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cEsEditableEBooleanParserRuleCall_6_0 = (RuleCall)cEsEditableAssignment_6.eContents().get(0);
		private final RuleCall cTSEMICOLONTerminalRuleCall_7 = (RuleCall)cGroup.eContents().get(7);
		private final Keyword cIsMandatoryKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final RuleCall cEQUALSTerminalRuleCall_9 = (RuleCall)cGroup.eContents().get(9);
		private final Assignment cEsRequeridoAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cEsRequeridoEBooleanParserRuleCall_10_0 = (RuleCall)cEsRequeridoAssignment_10.eContents().get(0);
		private final RuleCall cTSEMICOLONTerminalRuleCall_11 = (RuleCall)cGroup.eContents().get(11);
		private final Keyword cIsVisibleInListKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final RuleCall cEQUALSTerminalRuleCall_13 = (RuleCall)cGroup.eContents().get(13);
		private final Assignment cEsVisibleAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cEsVisibleEBooleanParserRuleCall_14_0 = (RuleCall)cEsVisibleAssignment_14.eContents().get(0);
		private final RuleCall cTSEMICOLONTerminalRuleCall_15 = (RuleCall)cGroup.eContents().get(15);
		private final Keyword cIsTitleKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final RuleCall cEQUALSTerminalRuleCall_17 = (RuleCall)cGroup.eContents().get(17);
		private final Assignment cEsTituloAssignment_18 = (Assignment)cGroup.eContents().get(18);
		private final RuleCall cEsTituloEBooleanParserRuleCall_18_0 = (RuleCall)cEsTituloAssignment_18.eContents().get(0);
		private final RuleCall cTSEMICOLONTerminalRuleCall_19 = (RuleCall)cGroup.eContents().get(19);
		private final Keyword cDataTypeKeyword_20 = (Keyword)cGroup.eContents().get(20);
		private final RuleCall cEQUALSTerminalRuleCall_21 = (RuleCall)cGroup.eContents().get(21);
		private final Assignment cTipoAssignment_22 = (Assignment)cGroup.eContents().get(22);
		private final RuleCall cTipoTipoDatoEnumRuleCall_22_0 = (RuleCall)cTipoAssignment_22.eContents().get(0);
		private final RuleCall cTSEMICOLONTerminalRuleCall_23 = (RuleCall)cGroup.eContents().get(23);
		private final RuleCall cTCLOSINGBRACETerminalRuleCall_24 = (RuleCall)cGroup.eContents().get(24);
		
		//Atributo:
		//	{Atributo}
		//	'Attribute' nombre=EString TOPENBRACE
		//	'isEditable' EQUALS esEditable=EBoolean TSEMICOLON
		//	'isMandatory' EQUALS esRequerido=EBoolean TSEMICOLON
		//	'isVisibleInList' EQUALS esVisible=EBoolean TSEMICOLON
		//	'isTitle' EQUALS esTitulo=EBoolean TSEMICOLON
		//	'dataType' EQUALS tipo=TipoDato TSEMICOLON
		//	TCLOSINGBRACE;
		@Override public ParserRule getRule() { return rule; }
		
		//{Atributo} 'Attribute' nombre=EString TOPENBRACE 'isEditable' EQUALS esEditable=EBoolean TSEMICOLON 'isMandatory' EQUALS
		//esRequerido=EBoolean TSEMICOLON 'isVisibleInList' EQUALS esVisible=EBoolean TSEMICOLON 'isTitle' EQUALS
		//esTitulo=EBoolean TSEMICOLON 'dataType' EQUALS tipo=TipoDato TSEMICOLON TCLOSINGBRACE
		public Group getGroup() { return cGroup; }
		
		//{Atributo}
		public Action getAtributoAction_0() { return cAtributoAction_0; }
		
		//'Attribute'
		public Keyword getAttributeKeyword_1() { return cAttributeKeyword_1; }
		
		//nombre=EString
		public Assignment getNombreAssignment_2() { return cNombreAssignment_2; }
		
		//EString
		public RuleCall getNombreEStringParserRuleCall_2_0() { return cNombreEStringParserRuleCall_2_0; }
		
		//TOPENBRACE
		public RuleCall getTOPENBRACETerminalRuleCall_3() { return cTOPENBRACETerminalRuleCall_3; }
		
		//'isEditable'
		public Keyword getIsEditableKeyword_4() { return cIsEditableKeyword_4; }
		
		//EQUALS
		public RuleCall getEQUALSTerminalRuleCall_5() { return cEQUALSTerminalRuleCall_5; }
		
		//esEditable=EBoolean
		public Assignment getEsEditableAssignment_6() { return cEsEditableAssignment_6; }
		
		//EBoolean
		public RuleCall getEsEditableEBooleanParserRuleCall_6_0() { return cEsEditableEBooleanParserRuleCall_6_0; }
		
		//TSEMICOLON
		public RuleCall getTSEMICOLONTerminalRuleCall_7() { return cTSEMICOLONTerminalRuleCall_7; }
		
		//'isMandatory'
		public Keyword getIsMandatoryKeyword_8() { return cIsMandatoryKeyword_8; }
		
		//EQUALS
		public RuleCall getEQUALSTerminalRuleCall_9() { return cEQUALSTerminalRuleCall_9; }
		
		//esRequerido=EBoolean
		public Assignment getEsRequeridoAssignment_10() { return cEsRequeridoAssignment_10; }
		
		//EBoolean
		public RuleCall getEsRequeridoEBooleanParserRuleCall_10_0() { return cEsRequeridoEBooleanParserRuleCall_10_0; }
		
		//TSEMICOLON
		public RuleCall getTSEMICOLONTerminalRuleCall_11() { return cTSEMICOLONTerminalRuleCall_11; }
		
		//'isVisibleInList'
		public Keyword getIsVisibleInListKeyword_12() { return cIsVisibleInListKeyword_12; }
		
		//EQUALS
		public RuleCall getEQUALSTerminalRuleCall_13() { return cEQUALSTerminalRuleCall_13; }
		
		//esVisible=EBoolean
		public Assignment getEsVisibleAssignment_14() { return cEsVisibleAssignment_14; }
		
		//EBoolean
		public RuleCall getEsVisibleEBooleanParserRuleCall_14_0() { return cEsVisibleEBooleanParserRuleCall_14_0; }
		
		//TSEMICOLON
		public RuleCall getTSEMICOLONTerminalRuleCall_15() { return cTSEMICOLONTerminalRuleCall_15; }
		
		//'isTitle'
		public Keyword getIsTitleKeyword_16() { return cIsTitleKeyword_16; }
		
		//EQUALS
		public RuleCall getEQUALSTerminalRuleCall_17() { return cEQUALSTerminalRuleCall_17; }
		
		//esTitulo=EBoolean
		public Assignment getEsTituloAssignment_18() { return cEsTituloAssignment_18; }
		
		//EBoolean
		public RuleCall getEsTituloEBooleanParserRuleCall_18_0() { return cEsTituloEBooleanParserRuleCall_18_0; }
		
		//TSEMICOLON
		public RuleCall getTSEMICOLONTerminalRuleCall_19() { return cTSEMICOLONTerminalRuleCall_19; }
		
		//'dataType'
		public Keyword getDataTypeKeyword_20() { return cDataTypeKeyword_20; }
		
		//EQUALS
		public RuleCall getEQUALSTerminalRuleCall_21() { return cEQUALSTerminalRuleCall_21; }
		
		//tipo=TipoDato
		public Assignment getTipoAssignment_22() { return cTipoAssignment_22; }
		
		//TipoDato
		public RuleCall getTipoTipoDatoEnumRuleCall_22_0() { return cTipoTipoDatoEnumRuleCall_22_0; }
		
		//TSEMICOLON
		public RuleCall getTSEMICOLONTerminalRuleCall_23() { return cTSEMICOLONTerminalRuleCall_23; }
		
		//TCLOSINGBRACE
		public RuleCall getTCLOSINGBRACETerminalRuleCall_24() { return cTCLOSINGBRACETerminalRuleCall_24; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.School.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.School.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean ecore::EBoolean:
		//	'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	
	public class TipoDatoElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.School.TipoDato");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cCadenaEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cCadenaSTRINGKeyword_0_0 = (Keyword)cCadenaEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cBoleanoEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cBoleanoBOOLEANKeyword_1_0 = (Keyword)cBoleanoEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cNumeroEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cNumeroNUMBERKeyword_2_0 = (Keyword)cNumeroEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cFechaEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cFechaDATEKeyword_3_0 = (Keyword)cFechaEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum TipoDato:
		//	cadena='STRING' | boleano='BOOLEAN' |
		//	numero='NUMBER' | fecha='DATE';
		public EnumRule getRule() { return rule; }
		
		//cadena='STRING' | boleano='BOOLEAN' | numero='NUMBER' | fecha='DATE'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//cadena='STRING'
		public EnumLiteralDeclaration getCadenaEnumLiteralDeclaration_0() { return cCadenaEnumLiteralDeclaration_0; }
		
		//'STRING'
		public Keyword getCadenaSTRINGKeyword_0_0() { return cCadenaSTRINGKeyword_0_0; }
		
		//boleano='BOOLEAN'
		public EnumLiteralDeclaration getBoleanoEnumLiteralDeclaration_1() { return cBoleanoEnumLiteralDeclaration_1; }
		
		//'BOOLEAN'
		public Keyword getBoleanoBOOLEANKeyword_1_0() { return cBoleanoBOOLEANKeyword_1_0; }
		
		//numero='NUMBER'
		public EnumLiteralDeclaration getNumeroEnumLiteralDeclaration_2() { return cNumeroEnumLiteralDeclaration_2; }
		
		//'NUMBER'
		public Keyword getNumeroNUMBERKeyword_2_0() { return cNumeroNUMBERKeyword_2_0; }
		
		//fecha='DATE'
		public EnumLiteralDeclaration getFechaEnumLiteralDeclaration_3() { return cFechaEnumLiteralDeclaration_3; }
		
		//'DATE'
		public Keyword getFechaDATEKeyword_3_0() { return cFechaDATEKeyword_3_0; }
	}
	
	private final RootElements pRoot;
	private final DetalleElements pDetalle;
	private final EntidadElements pEntidad;
	private final AtributoElements pAtributo;
	private final EStringElements pEString;
	private final EBooleanElements pEBoolean;
	private final TipoDatoElements eTipoDato;
	private final TerminalRule tTOPENBRACE;
	private final TerminalRule tTCLOSINGBRACE;
	private final TerminalRule tTSEMICOLON;
	private final TerminalRule tEQUALS;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public SchoolGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pRoot = new RootElements();
		this.pDetalle = new DetalleElements();
		this.pEntidad = new EntidadElements();
		this.pAtributo = new AtributoElements();
		this.pEString = new EStringElements();
		this.pEBoolean = new EBooleanElements();
		this.eTipoDato = new TipoDatoElements();
		this.tTOPENBRACE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.School.TOPENBRACE");
		this.tTCLOSINGBRACE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.School.TCLOSINGBRACE");
		this.tTSEMICOLON = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.School.TSEMICOLON");
		this.tEQUALS = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.School.EQUALS");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.School".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Root:
	//	{Root}
	//	'Application' nombre=EString TOPENBRACE
	//	'navBarColorHex' EQUALS navBarColorHex=EString TSEMICOLON
	//	'textColor' EQUALS textColor=EString TSEMICOLON
	//	'floatingButtonColor' EQUALS floatingButtonColor=EString TSEMICOLON
	//	entidad+=Entidad+
	//	detalles+=Detalle*
	//	TCLOSINGBRACE;
	public RootElements getRootAccess() {
		return pRoot;
	}
	
	public ParserRule getRootRule() {
		return getRootAccess().getRule();
	}
	
	//Detalle:
	//	{Detalle}
	//	'Detail' name=ID TOPENBRACE
	//	'isStrong' EQUALS esFuerte=EBoolean TSEMICOLON
	//	entidad=[Entidad] TCLOSINGBRACE;
	public DetalleElements getDetalleAccess() {
		return pDetalle;
	}
	
	public ParserRule getDetalleRule() {
		return getDetalleAccess().getRule();
	}
	
	//Entidad:
	//	{Entidad}
	//	'Entity' name=ID TOPENBRACE
	//	'description' EQUALS descripcion=EString TSEMICOLON
	//	atributo+=Atributo+
	//	detalles+=[Detalle]*
	//	TCLOSINGBRACE;
	public EntidadElements getEntidadAccess() {
		return pEntidad;
	}
	
	public ParserRule getEntidadRule() {
		return getEntidadAccess().getRule();
	}
	
	//Atributo:
	//	{Atributo}
	//	'Attribute' nombre=EString TOPENBRACE
	//	'isEditable' EQUALS esEditable=EBoolean TSEMICOLON
	//	'isMandatory' EQUALS esRequerido=EBoolean TSEMICOLON
	//	'isVisibleInList' EQUALS esVisible=EBoolean TSEMICOLON
	//	'isTitle' EQUALS esTitulo=EBoolean TSEMICOLON
	//	'dataType' EQUALS tipo=TipoDato TSEMICOLON
	//	TCLOSINGBRACE;
	public AtributoElements getAtributoAccess() {
		return pAtributo;
	}
	
	public ParserRule getAtributoRule() {
		return getAtributoAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//EBoolean ecore::EBoolean:
	//	'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//enum TipoDato:
	//	cadena='STRING' | boleano='BOOLEAN' |
	//	numero='NUMBER' | fecha='DATE';
	public TipoDatoElements getTipoDatoAccess() {
		return eTipoDato;
	}
	
	public EnumRule getTipoDatoRule() {
		return getTipoDatoAccess().getRule();
	}
	
	//terminal TOPENBRACE:
	//	"{";
	public TerminalRule getTOPENBRACERule() {
		return tTOPENBRACE;
	}
	
	//terminal TCLOSINGBRACE:
	//	"}";
	public TerminalRule getTCLOSINGBRACERule() {
		return tTCLOSINGBRACE;
	}
	
	//terminal TSEMICOLON:
	//	";";
	public TerminalRule getTSEMICOLONRule() {
		return tTSEMICOLON;
	}
	
	//terminal EQUALS:
	//	"=";
	public TerminalRule getEQUALSRule() {
		return tEQUALS;
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
