/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SchoolStandaloneSetup extends SchoolStandaloneSetupGenerated {

	def static void doSetup() {
		new SchoolStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
